[package]
name = "tokio-my-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"

# needed by mini-tokio of future-delay.rs example
futures = "0.3"
crossbeam = "0.8"