#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=pi@raspberrypi
readonly TARGET_PATH=/home/pi/raspi-crosscompile
readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly SOURCE_PATH="$(dirname "$0")"/target/${TARGET_ARCH}/release/raspi-crosscompile

cargo build --release --target=${TARGET_ARCH}
#rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
#ssh -t ${TARGET_HOST} ${TARGET_PATH}
